### ISSUE TITLE
Raspberry PI4 : Nodejs - javascript - ssd1306 oled

### ISSUE THREAD

**Issue by yboujraf** [deeplyembeddedWP/SSD1306-OLED-display-driver-for-BeagleBone#5]
Dear @deeplyembeddedWP , @giuliomoro 

I hope you are well.

I have seen you are using on beaglebone the adafruit-ssd1306 in c and I2C.

From my side I am using Raspberry PI4 and I'd like to know if I clone the repository except to activate the I2C and maybe pins for I2C it should work?

Otherwise, is it possible to adapt the c library in javascript to use it with nodejs ?

If yes thanks if you could share how to make it.

Best Regards
Youssef

**Comment by vinay-divakar** [comment]
The c library should work fine if you have the i2c working and the right connections in place. I am not sure about your second question.

**Comment by yboujraf** [comment]
Dear @deeplyembeddedWP 

That means all the c library from adafruit could be used in beagleboone or raspberry ? Is it right ?

I have seen for python library but not in another language.

Best Regards
Youssef

**Comment by vinay-divakar** [comment]
The [C++ library by Adafruit](https://github.com/adafruit/Adafruit_SSD1306) is for Arduino Uno which uses an Atmel controller so it won't work on the Beaglebone. And this library is for Beaglebone but should be compatible with the pi as well since I use the standard Linux API's in the I2C library.

**Comment by vinay-divakar** [comment]
Closing presuming this thread is no longer active.
